name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    # Change from ubuntu-latest to self-hosted so it runs locally on your laptop
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      # Using standard shell commands since your local machine already has Python & Docker
      name: Run Tests
      run: |
        pip install -r api/requirements.txt
        pip install pytest
        pytest api/tests
      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-api:${{ github.sha }}
      - name: Deploy to Minikube Cluster
        run: |
          # Since it runs on your laptop, kubectl already has direct access!
          kubectl set image deployment/flask-api flask-api=${{ secrets.DOCKERHUB_USERNAME }}/flask-api:${{ github.sha }}
